sudo: required
dist: trusty
services:
    - docker
script:
    - mkdir -p "$HOME/.config/snapcraft"
    - '[ -e "$HOME/.config/snapcraft/snapcraft.cfg" ] || echo "$SNAPCRAFT_CONFIG" > "$HOME/.config/snapcraft/snapcraft.cfg"'
    - docker run -v $HOME:/root -v $(pwd):/cwd didrocks/snapcraft sh -c 'cd /cwd; snapcraft'
cache:
    directories:
        - "$HOME/.config"
after_success:
    - '[ "${TRAVIS_BRANCH}" = "edge" ] && docker run -v $HOME:/root -v $(pwd):/cwd didrocks/snapcraft sh -c "cd /cwd; snapcraft push *.snap --release edge"'
    - '[ "${TRAVIS_BRANCH}" = "master" ] && docker run -v $HOME:/root -v $(pwd):/cwd didrocks/snapcraft sh -c "cd /cwd; snapcraft push *.snap --release stable"'
