sudo: required
secure: "FABaJ1wthRsHHdTV9OI7TmDYrSSS3SbrHlJ7lXLYfx8bwqscLzJ6e/QilmrgSwGE4+H4P96MfQjvuPmn7FJk1DdGb9XdQrNonp5bJHYMerASiXo+Rb0C5UylRiLZn+mmfbLJ2Z4ig4sSju4+KVbNqmAWqNKY/Y08fdczQiLR/XgpDIA8uH43IQOyjZ0V+mUptNcDcue4ZZlfy6v3AI41E/mMUj2u3lqH83/IoKlzzzfk5an6fCoTLoRckbzrXt3kcDduUZsXoVqwt4IfMsR5yMa3qAOiV3jk3hYIfMg+ppqgyN+CDzUquyQLY1eobL30GO3NRXSvTdgdclMik7ZY5il34oGS5JNKTlxHhu49QoiehBegXCIrAVox1tAyEu4IRQZGd3ESr4ToCFvFvChqRgxKbEuInA9zC1HP8LpTLnqCuVf1tQ3xOO6VYaSUGma4wWSDrXB4sRvS37rkVEemRWOj8l/ZDGhtTrpTdwgsHkFWGOdsX8iaMfROyL1JFZPYvQneBqwuDMIqGHvnfrCmuXLHx8zIFVBkfTbBzzN1fuvKfsDmwRqelbOx4b5RvMtmGU0YCdTaX70g41y5Kj7TNfKVvGkiPtySrILZOTRLZsBzZ2Cd2A7z23jjdDWxZ38qtSodHWAx3zwhWahVR0VIbCLaTwnTK1TqQOkqzWRIwrc="
services:
    - docker
language: python
python:
    - "3.5"
install:
    - pip3 install requests
script:
    - docker run -v $(pwd):/snapcraft didrocks/snapcraft sh -c 'cd /snapcraft; snapcraft'
after_success:
    - ./upload_to_store
