name: cassandra
version: 3.5
summary: Cassandra distributed database
description: The Apache Cassandra database
confinement: strict
apps:
    cassandra:
        command: cassandra-wrapper -f -R
        daemon: simple
        # mount-observe is needed for checking available space in the data
        # directories (java.io.File.getTotalSpace). It must be manually
        # connected with:
        # `snap connect cassandra:mount-observe ubuntu-core:mount-observe`
        plugs: [network, network-bind, mount-observe]
        # The setpriority syscall is also needed, but currently unavailable:
        # https://bugs.launchpad.net/snappy/+bug/1577520
    config-get:
        command: config-get
    config-set:
        command: config-set
parts:
    cassandra:
        plugin: cassandra
        source: git://github.com/apache/cassandra
        source-tag: cassandra-3.5
        stage-packages:
            - mawk
            - grep
            # For /usr/bin/free
            - procps
        organize:
            conf: etc/cassandra
            bin/cassandra: usr/sbin/cassandra
            lib: usr/share/cassandra/lib
            usr/bin/mawk: usr/bin/awk
        snap:
            - etc/cassandra
            - usr/sbin/cassandra
            - usr/share/cassandra/lib/*.jar
            - usr/lib/jvm
            # These three needed by cassandra-env.sh
            - usr/bin/awk
            - bin/grep
            - usr/bin/free
    glue:
        plugin: copy
        files:
            wrapper: bin/cassandra-wrapper
            config-get: bin/config-get
            config-set: bin/config-set
            common: bin/common

# vim: set ai et sts=4 tabstop=4 sw=4:
